export const GET_SUB_APP_REQUESTED = "GET_SUB_APP_REQUESTED";
export const GET_SUB_APP_SUCCESS = "GET_SUB_APP_SUCCESS";
export const GET_SUB_APP_FAILED = "GET_SUB_APP_FAILED";
export const SET_APPLICATION_DRP_STATUS = "SET_APPLICATION_DRP_STATUS";
export const SET_LANGUAGE = "SET_LANGUAGE";
export const SET_LANGUAGE_DRP_STATUS = "SET_LANGUAGE_DRP_STATUS";